// src/content/modules/module-09-pathologies.ts
import { Module } from '../../types/content';

export const module09: Module = {
  id: 'pathologies',
  number: 9,
  title: 'Patologías Neuromusculares y Patrones Electrodiagnósticos',
  titleEn: 'Neuromuscular Pathologies and Electrodiagnostic Patterns',
  emoji: '🩺',
  description: 'Neuropatías, miopatías, enfermedades de motoneurona, trastornos de UNM y más',
  descriptionEn: 'Neuropathies, myopathies, motor neuron diseases, NMJ disorders and more',
  color: 'from-red-500 to-red-800',
  icon: 'Stethoscope',
  topics: [
    { id: 'peripheral-neuropathies', title: 'Neuropatías Periféricas', children: [
      { id: 'axonal-vs-demyelinating', title: 'Clasificación: axonal vs. desmielinizante vs. mixta', content: 'Axonal: pérdida de amplitud de CMAP/SNAP con conducción (VCM/VCS) conservada (>75% LIN). Desmielinizante: latencias distales prolongadas, VCM/VCS marcadamente enlentecidas (<70% LIN), bloqueos de conducción y dispersión temporal anormal.' },
      { id: 'diabetic-neuropathy', title: 'Polineuropatía diabética', content: 'Causa polineuropatía más frecuente. Patrón axonal sensitivo-motor clásico con distribución longitud-dependiente (stocking-glove). SNAP surales disminuyen primero, luego peroneos, tardíamente nervios de extremidad superior. A menudo se asocia con un enlentecimiento desmielinizante muy leve secundario a la pérdida de fibras gruesas.' },
      { id: 'alcoholic-toxic', title: 'Neuropatía alcohólica y tóxica', content: 'Patrón axonal sensitivo-motor típicamente longitud-dependiente. La neuropatía inducida por alcohol resulta frecuentemente de una deficiencia nutricional concurrente (B1/tiamina) o toxicidad directa. EMG muestra desinervación (fibrilaciones) distal temprana.' },
      { id: 'small-fiber', title: 'Neuropatía de fibra fina', content: 'NCS de rutina son NORMALES (solo evalúan fibras propioceptivas mielinizadas gruesas). Dolor severo/quemante idiopático, diabético o amiloidótico. Requiere pruebas autonómicas, reflejo axónico cuantitativo (QSART) o biopsia de piel (baja densidad epidérmica).' },
      { id: 'chemo-neuropathy', title: 'Neuropatía por quimioterapia', content: 'Mayormente produce una axonopatía sensitiva. Platinos (cisplatino/oxaliplatino) causan ganglioneuropatía dorsal, resultando en SNAPs ausentes globalmente con CMAP conservado. Taxanos/alcaloides de la vinca causan polineuropatía sensitivo-motora distal.' },
      { id: 'amyloidosis', title: 'Amiloidosis', content: 'Frecuentemente inicia como fibra fina dolorosa con afectación autonómica severa antes de progresar a fibra gruesa. Un túnel carpiano bilateral y muy severo refractario a cirugía suele ser una señal temprana patognomónica de amiloidosis AL/TTR.' },
      { id: 'cmt', title: 'Heredopatías: Charcot-Marie-Tooth', children: [
        { id: 'cmt1', title: 'CMT tipo 1 (desmielinizante)', content: 'VCM uniformemente lentas en todos los nervios (ej., mediano <38 m/s, frecuentemente 15-25 m/s). PMP22 duplicación (CMT1A) es la más común. A diferencia de las polineuropatías adquiridas (CIDP), hay AUSENCIA de bloqueos de conducción focales y dispersión temporal anormal porque la desmielinización es congénita y homogénea.' },
        { id: 'cmt2', title: 'CMT tipo 2 (axonal)', content: 'Mutaciones (p. ej., MFN2 en CMT2A). CMAP y SNAP con amplitudes residuales minúsculas pero velocidades solo discretamente reducidas (>38 m/s). Cambios miopáticos crónicos compensatorios en EMG.' },
        { id: 'cmt-others', title: 'CMT tipos 3, 4, X', content: 'CMT3 (Dejerine-Sottas): hipertrófica, infantil severa con VCM <10 m/s. CMTX: ligada al cromosoma X, varones afectados más severamente, puede presentar una rara "desmielinización desigual" o mixta que asemeja procesos adquiridos.' },
      ]},
      { id: 'hnpp', title: 'HNPP (predisposición a parálisis por presión)', content: 'Deleción genética recíproca de PMP22. Presenta mononeuropatías focales transitorias en sitios comunes de compresión física (codo, túnel carpiano, cabeza del peroné). Hallazgo NCS principal: latencias focales desmielinizantes en estos sitios superpuestas sobre polineuropatía de base difusa.' },
    ]},
    { id: 'inflammatory-neuropathies', title: 'Neuropatías Inflamatorias', children: [
      { id: 'gbs', title: 'Síndrome de Guillain-Barré (SGB)', children: [
        { id: 'aidp', title: 'AIDP (desmielinizante aguda)', content: 'Forma predominante en occidente. "Patrón de preservación sural" (Sural Sparing Pattern) es altamente característico tempranamente: los SNAPs de extremidades superiores (mediano/ulnar) están ausentes/anormales, mientras que el SNAP Sural es normal paradójicamente. Más tarde muestra latencias distales excesivas, LMD y bloqueos.' },
        { id: 'aman-amsan', title: 'AMAN y AMSAN (variantes axonales)', content: 'Formas puramente motoras (AMAN) o sensitivo-motoras (AMSAN) mediadas por anticuerpos (GM1, GD1a). AMAN puede manifestar "Fallo de Conducción Reversible (RCF)": depósitos de Ac en Nodos de Ranvier bloquean la conducción al inicio, simulando un bloqueo desmielinizante, que se resuelve muy rápidamente de manera atípica para un GBS tradicional.' },
        { id: 'fisher', title: 'Síndrome de Miller Fisher (MFS)', content: 'Forma craneal (Anti-GQ1b positivo). Triada: oftalmoplejía, arreflexia, ataxia. NCS: amplitudes SNAP característicamente muy reducidas tempranamente (pérdida gangliónica) con CMAPs normales. Ondas F rutinariamente ausentes del principio. Latencias prolongadas de reflejo de parpadeo (blink reflex) R1 y R2.' },
        { id: 'gbs-temporal', title: 'Hallazgos por etapa temporal', content: 'Primeros 7 días: anomalías de Onda F o ausencia de reflejo H (hallazgo más temprano). Semanas 1-3: desarrollos completos de bloqueos de conducción y enlentecimientos (criterios Hadden). Semana >3: la EMG de aguja revela verdadera denervación (fibrilaciones) si existió daño axonal concomitante.' },
      ]},
      { id: 'cidp', title: 'PDIC (CIDP)', children: [
        { id: 'ean-pns-criteria', title: 'Criterios Diagnostic EAN/PNS 2021', content: 'Han reemplazado a EFNS 2010. Fuerte requisito de alteraciones en nervios motores Y anomalías evidentes también en exploración sensitiva en "CIDP Típico". Determina VCM lenta (≤70%) y alteraciones duraderas como bloqueos en >2 nervios independientes.' },
        { id: 'cidp-variants', title: 'Variantes de CIDP', content: 'Lewis-Sumner (MADSAM): asimétrica y focal pero presenta alteración SNAP en los fascículos afectados, a diferencia de NMM. Distal Adquirida (DADS): fenotipo fuertemente simétrico y distal mediado frecuentemente por inmunoglobulina monoclonal (anti-MAG IgG/IgM).' },
        { id: 'autoimmune-nodopathies', title: 'Nodopatías Autoinmunes (¡Clave!)', content: 'Condiciones emergentes distintas a CIDP. Anticuerpos IgG4 contra complejos Nodo de Ranvier (Neurofascin-155, Contactin-1, Caspr1). Patrón NCS: graves bloqueos de conducción pero asociados a un daño axonal inmediato primario temprano (nodopatía verdadera). ¡Clínicamente no responden a IVIg rutinario y requieren Rituximab!' },
      ]},
      { id: 'mmn', title: 'Neuropatía Motora Multifocal (NMM)', children: [
        { id: 'mmn-block', title: 'Bloqueo de conducción diagnóstico (NMM)', content: 'Definido por bloqueos focales motores puros (caída masiva de CMAP >50%) entre dos puntos de estimulación que NO corresponden a atrapamientos biomecánicos normales (ej. a mitad de brazo o muslo). Crucial: estimulación del componente sensitivo del mismo trayecto nervioso es perfectamente normal.' },
        { id: 'anti-gm1', title: 'Autoinmunidad y anti-GM1', content: 'Presencia de IgM anti-GM1 fuertemente indicativa (~50-80% sensibilidad). Presentación clínica: debilidad progresiva flácida en banda distal de extremidad superior, atrofia asimétrica simulando ELA, pero estricta supervivencia de sistema nervioso motor central (sin signos de UMN o bulbos).' },
      ]},
    ]},
    { id: 'mononeuropathies', title: 'Mononeuropatías y Atrapamientos', children: [
      { id: 'carpal-tunnel', title: 'Síndrome del túnel carpiano', children: [
        { id: 'cts-comparison', title: 'Estudios de comparación (mediano vs. ulnar)', content: 'La diferencia de latencia sensitiva mediano-ulnar al 4to dedo (lumbrical-interóseo) >0.4-0.5 ms es el estudio más sensible para STC inicial. Comparaciones alternativas para diagnóstico en casos grises incluyen variaciones de mediano-radial en el pulgar.' },
        { id: 'cts-severity', title: 'Clasificación de severidad', content: 'Leve: lentitud focal puramente sensitiva trans-carpal. Moderado: retraso patológico en la latencia motora del CMAP (LMD prolongada). Severo: reducción grave persistente en la amplitud CMAP motora (< 4 mV). Extremo: inexcitabilidad total de APB y denervación activa robusta en EMG de aguja.' },
        { id: 'cts-emg', title: 'Rol de la EMG en STC', content: 'El muestreo en Abductor Pollicis Brevis (APB) determina denervación axónica verdadera (fibrilaciones) que guían pronóstico post-quirúrgico. El examen rutinario también incluye Pronator Teres u otros músculos proximales del mediano para descartar atrapamiento alto o radiculopatía C6-C7.' },
      ]},
      { id: 'ulnar-elbow', title: 'Neuropatía cubital en codo (UNE)', children: [
        { id: 'inching-elbow', title: 'Neurometría Inching a través del codo', content: 'Desplazamiento proximal incremental del cátodo a pasos fijos de 1 a 2 cm cruzando el codo (epicóndilo-surco). Un cambio adyacente focal masivo de latencia (> 0.4 ms) o caída anatómica de amplitud aísla la porción exacta comprometida.' },
        { id: 'guyon-canal', title: 'Canal de Guyon', content: 'Diferencial clave para UNE. NCS conservada cruzando el codo pero con CMAP hipotenar o FDI (Primer interóseo dorsal) aislado retardado o reducido en la muñeca. El SNAP dorsal cutáneo del ulnar debe estar NORMAL en retención en el túnel de Guyon, ayudando a diferenciación etiológica.' },
      ]},
      { id: 'radial-neuropathy', title: 'Neuropatía radial y otras de MS', content: 'Parálisis del sábado por la noche en la canaladura espiral del húmero (compresión compresiva axonal) mostrando muñeca caída. CMAP extensor digitorum caido, pero tríceps respetado. Diferencias postcervicales C7 y PIN (nervio interóseo posterior) - este último no causa caída pura extensora y respeta nervios sensoriales.' },
      { id: 'peroneal-neuropathy', title: 'Neuropatía peronea superficial', content: 'Causa unilateral más habitual de pie caído agudo. Muestra enlentecimiento dramático y posible bloqueo cruzando la cabeza fibrilar/cuello peroné lateral de la pierna en grabación de Extensor Digitorum Brevis o Tibial Anterior. El SNAP de peroneo superficial está comúnmente deprimido.' },
      { id: 'tarsal-tunnel', title: 'Síndrome del Túnel Tarsiano', content: 'Compresión tibial en tobillo sub-retinacular medial. CMAP retardado al abductor hallucis y digiti minimi. Extremadamente propenso a errores térmicos falsos de miembros gélidos (<30 C). Diferenciar rutinariamente con neuropatía de fibra nerviosa distal general (polineuropatía).' },
      { id: 'bells-palsy', title: 'Parálisis de Bell (nervio facial)', content: 'Prueba NCS motor al día 7-10 post-inicio: una respuesta o área reducida en el lado enfermo a menos del 10% del homólogo sano indica denervación walleriana de mal pronóstico rehabilitador. El Blink Reflex evalúa arcos polisinápticos subcorticales V-VII (onda R1 aferente tardía es patognomónica de daño proximal).' },
    ]},
    { id: 'radiculopathies', title: 'Radiculopatías', children: [
      { id: 'cervical-radic', title: 'Radiculopatía cervical (C5-T1)', content: 'Hallazgo base: patrón radicular selectivo anatómico miotomal en EMG. Los músculos espinales paraxiales (paraespinales cervicales) frecuentemente denervados apoyan fuertemente origen radicular proximal. CRÍTICO: SNAPs se mantienen MÁS QUE NORMALES independientemente del daño sensitivo, por preganglionicidad intraspinal anatómica.' },
      { id: 'lumbosacral-radic', title: 'Radiculopatía lumbosacra (L4, L5, S1)', content: 'L5 es la raíz patológica más frecuentemente comprimida. En L5 CMAP Extensor digitorum brevis y Tibial anterior denervados. S1 presentará atenuación característica masiva o retardo absoluto subyacente de Reflejo H con atrofia de gastrocnemio medial.' },
      { id: 'paraspinal-role', title: 'Relevancia espinal obligatoria', content: 'La prueba de paraespinales y multífidos mediales diferencia lesiones intraspinales vs plexos. Sangran profusamente, pero resultan positivos fibrilares apenas a los 7-10 días (mucho más rápido que las 3-4 semanas distales extremidades) debido a cercanía física patológica de compresión de raíz.' },
      { id: 'radic-vs-plexopathy', title: 'Radiculopatía vs. Plexopatía', content: 'Dicotomía absoluta anatómica patológica NCS. RADICULOPATÍA (pre-ganglionar): NCS SNAPs puramente normales pero clínica hiperestésica + Fibrilaciones en paraespinales. PLEXOPATÍA (post-ganglionar): Amplitud de SNAPs globalmente destruidos por distorsión neurotroncal posterior de GRD + paraespinales absolutamente librados de denervación.' },
    ]},
    { id: 'plexopathies', title: 'Plexopatías', children: [
      { id: 'traumatic-bp', title: 'Trauma Plexo Braquial', content: 'Comúnmente avulsiones traumáticas obstétricas o accidentes motores (Erb-Duchenne en C5-C6 troncos superiores / Klumpke en C8-T1 inferior). Requiere NCS minuciosa global y EMG extensa en músculos clave escapulares (Serrato Anterior para Torácica Larga, Romboides para Dorsal Escapular - raíces extra preplexales absolutas).' },
      { id: 'radiation-bp', title: 'Plexopatía inducida por radiación', content: 'Caracterizada crónicamente contra tumor neoplásico. Invasión neoplásica duele horriblemente aguda y apunta tronco pélvico inferior. Radiación no duele tanto general y afecta pancoast troncos anatómicos superiores. El EMG de agujas en la forma post-retardada irradiatoria evidencia MIOQUIMIAS robustas (espasmosis agrupadas), siendo diagnóstico principal diferencial.' },
      { id: 'parsonage-turner', title: 'Síndrome de Parsonage-Turner', content: 'Neuralgia Amiotrófica Idiopática severa dolorosísima braquial. Desmielinización inflamatoria brutal que destruye focos aleatorios de raíces altas. Conducción SNAPs ausente en radiales laterales pero NCS preservado en cubital. Se revela por atrofia muscular atípica masiva selectiva 1 semana de fase inflamatoria y fibrilación masiva en varios territorios.' },
      { id: 'lumbosacral-plexopathy', title: 'Plexopatía Lumbosacra y Amiotrofia Diabética', content: 'Síndrome de Bruns-Garland clásico en diabéticos asimétricos ancianos (radiculoplexoneuropatía lumbosacra inducida autoinmune-isquémica). Destroza dolorosamente nervio femoral-cuádriceps aislados unilateralmente con SNAP safeno masivamente mermado. Tumores retroperitoneales aplastan crónicamente porciones lumbo-caudales.' },
    ]},
    { id: 'motor-neuron-diseases', title: 'Enfermedades de la Motoneurona', children: [
      { id: 'als', title: 'Esclerosis Lateral Amiotrófica (ELA)', children: [
        { id: 'gold-coast', title: 'Criterios Modernos (Gold Coast 2019)', content: 'Nuevos criterios que eliminan clasificaciones "posible/probable" del viejo Awaji/El Escorial. ELA se consolida con UMN + LMN simultáneo central progresivo o LMN general en +2 zonas. En neurociencia EMG las Fasciculaciones Complejas equivalen a Denervación Activa estricta para suma diagnóstica directa final.' },
        { id: 'als-emg-role', title: 'Tríada EMG Diagnóstica en ELA', content: 'Reclutamiento MUAP neurogénico de fuego desquiciadamente hiperrápido pero con unidades escasamente operativas masivas "gigantes" (por reinervación colateral a largo plazo de neuronas adyacentes sobrevivientes activas extremas). Esto sumado a Fibrilación y Fasciculación ubicuamente difusa craneal, axilar, abdominal y crural subraya diagnóstico.' },
        { id: 'als-differential', title: 'Diferenciación crucial con CIDP/NMM', content: 'Siempre evitar confundir una variante lumbosacra lenta MMN tratable subdiagnósticada de "ELA". Para ELA las velocidades nerviosas de neuroconducción permanecen perfectas e intrínsecamente sanas con desmielinización cero. Ausencia de dolor radicular o sensorial, con SNAP 100% vital sano residual intacto.' },
      ]},
      { id: 'kennedy', title: 'Enfermedad de Kennedy', content: 'Forma bulboespinal asintomática motora sexual genética recesiva X repetida. Confunde al neurólogo inicialmente pero EMG difiere a motor neurona clásica por reducción extrema postganglional simpática en atenuación masiva universal atípica de SNAPs sensitivas.' },
      { id: 'sma', title: 'Atrofia Muscular Espinal (AME)', content: 'Degeneración LMN autosómica patológica gen SMN1 pura severa infantil Werdnig-Hoffmann pre-pubertad. En EMG los potenciales de reclutamiento son increíblemente masivos (hiper-neurogénicos). No cruzan nunca barrera nerviosa sensorial como se ve típicamente en polineuropatías adquiridas tóxicas.' },
    ]},
    { id: 'nmj-disorders', title: 'Trastornos de la Unión Neuromuscular', children: [
      { id: 'myasthenia', title: 'Miastenia Gravis', children: [
        { id: 'mg-rns', title: 'ENR - Estimulación Neuronal Repetitiva', content: 'Test diagnóstico basal motor. Disparos nerviosos lentos secuenciales de 2Hz a 3Hz determinan falla placa motora acetilcolina causando "caída" (decremento clásico forma de silla de montar) de CMAP inicial a 4to pulso >10%.' },
        { id: 'mg-sfemg', title: 'SFEMG - Electromiografía Fibra Única', content: 'Alta destreza y altísima especificidad/sensibilidad global. Aumento estadístico crítico de la variabilidad subyacente temporal ("Jitter") al comparar 2 fibras musculares sincrónicas motor-unidades con aguja monocular. Jitter patológicamente agrandado o con fenómenos ausentes (Blocking).' },
      ]},
      { id: 'lems', title: 'Síndrome Lambert-Eaton', children: [
        { id: 'lems-rns', title: 'Facilitación Presináptica al Ejercicio', content: 'Causa autoinmunitaria canal-calcio pulmonar microcítico central. Inicial en EDX: CMAPs con amplitudes base absurdamente ínfimas débiles general. Un ejercicio de contención voluntaria de fuerza extrema paciente 10 segundos inyecta Ca2+ al terminal nervioso "arreglándolo" y generando >100% de masivo incremento basal transitorio post ejercicio del CMAP amplitude.' },
      ]},
      { id: 'botulism', title: 'Botulismo', content: 'Semeja en hallazgos electromiográficos severamente el presináptico fisiológico base defecto Lambert-Eaton en NCS/ENR con amplitudes CMAP deprimentemente iniciales ausentes con potenciaciones sutiles. Se suma denervación química EMG difusamente agresiva sistémica por desconexión nervio terminal presináptica final irreversible en fibras musculares periféricas.' },
    ]},
    { id: 'myopathies', title: 'Miopatías', children: [
      { id: 'inflammatory-myopathies', title: 'Miopatías inflamatorias (Polimiositis)', content: 'NCS perfectos globalmente. EMG aguja penetrante muscular evidencia Tríada Miopática Agresiva: PUMs excesivamente deprimidos y cortísimos (Poli-Pequeños) asociados con reclutamiento ultra-temprano compensador absurdo poblacional sinérgeticamente ligados permanentemente a presencia incesante de Desinervaciones espigadas PSW y Fibrilar necrosis invasora.' },
      { id: 'ibm', title: 'Miositis por Cuerpos Inclusión (IBM)', content: 'CRÍTICO: Condición miopática anciana peculiar que genera confusión debido a mostrar un "PATRÓN MIXTO" hibrido. PUMs miopáticos coexisten en paralelo engañosamente en misma inserción aguja con abundantes PUMs masivos gigantes típicamente patognomónicos asimilables neurogénicos de vieja cronología residual y desgarramiento fibras compensatorios secundarios espinales motoneuronales simulando falsamente a esclerosis (ELA) pura o mononeural radiculopatía mixta compleja.' },
      { id: 'muscular-dystrophies', title: 'Distrofias Genéticas (Duchenne y DM)', content: 'En Duchenne infantes ausencia proteína distrofina crea descargas miopáticas severas, pero en adulto la manifestación miopata predominante por defecto intergeneracional canal C-T-G (Enfermedad de Steinert "DM1") introduce el signo electromiográfico universalmente audible: Fenómeno miotónico musical tipo bombardeos decreciente picada con PUM miopático concomitante masivo residual.' },
      { id: 'channelopathies', title: 'Canalopatías y Parálisis Periódicas', content: 'Es fundamental el protocolo diagnóstico por ejercicio físico diferenciando: "Test Exercicio Corto Repetido" identifica variabilidades canaliculares tempranas musculares mientotónicas de cloruro/sodio vs "Test Protocolar Ejercicio Clínico Prolongado Continuo de McManis" desencadena decrementos patológicos latentes tardíos inducidos isquémicos muy críticos en las parálisis distróficas transitorias hiper/hipopotasiémicas escondindas.' },
      { id: 'myopathic-vs-neurogenic', title: 'Diagnóstico PUM Clásico Consolidado Picos', content: 'MIOPÁTICO: Fuerza y sincronía mermada intracelular por lisis miocitos produce PUM minúsculos deprimentes cortísimos de latencia deprimidísima (<8ms y apenas 300mV) pero sobrepobla su encendido disparo (reclutamiento anticipado). NEUROGÉNICO: ELA/Neuropatía mata motoneurona central madre y la célula gemela espinal remanente hipertrofiada se agrupa en un súper-axón generando PUM masivos aberrantes grandulones espaciados temporales de reducida cadencia pero altísima durada y volumen amplio.' },
    ]},
  ]
};
